apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppal-config
  namespace: shoppal
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "shoppal"
  NODE_ENV: "production"
  SUPPORT_ALLOWED_ORIGINS: "https://shop.example.com,http://localhost:5173"
  NOTIFICATIONS_URL: "http://notifications:8082"
  SUPPORT_SERVICE_URL: "http://support:8081"
